config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  root to: 'static_pages#home'

  get  'pages/about'

  resources :competitions

  devise_for :users

end

app/models/competition.rb
class Competition < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_token_authenticatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :competitions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   before_filter :store_location

 
   acts_as_token_authentication_handler_for User, fallback_to_devise: false
  protect_from_forgery with: :null_session

 
def store_location
  # store last url - this is needed for post-login redirect to whatever the user last visited.
  return unless request.get? 
  if (request.path != "/users/sign_in" &&
      request.path != "/users/sign_up" &&
      request.path != "/users/password/new" &&
      request.path != "/users/password/edit" &&
      request.path != "/users/confirmation" &&
      request.path != "/users/sign_out" &&
      !request.xhr?) # don't store ajax calls
    session[:previous_url] = request.fullpath 
    Rails.logger.info "message1"
    Rails.logger.info request.fullpath 
    
  end
end
 

  def after_sign_in_path_for(resource)
  	Rails.logger.info "message"
   session[:previous_url] 
   
   
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_filter :store_location
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show] 
  before_action :correct_user, only: [:edit, :update, :destroy]
respond_to :html, :json 

  def index
    @competitions = Competition.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
    respond_with(@competitions)
  end

  def show
    respond_with(@competition)
  end

  def new

      @competition = current_user.competitions.build
      respond_with(@competition)
    


  end

  def edit
  end

  def create
    @competition = current_user.competitions.new(competition_params)
    @competition.save
    respond_with(@competition)
  end

  def update
    @competition.update(competition_params)
    respond_with(@competition)
  end

  def destroy
    @competition.destroy
    respond_with(@competition)
  end

  private

    def set_competition
      @competition = Competition.find(params[:id])
    end

    

    def correct_user
        @competition = current_user.competitions.find_by(id: params[:id])
        redirect_to competitions_path, notice: "Not authorized to edit this pin" if @competition.nil?

    end

    def competition_params
      params.require(:competition).permit(:name,:category, :description, :collegename, 
        :money, :onOff,:location,:startDate,:endDate,:organizedBy,:linkWebsite,:linkWebsite,:linkFb,:startDateText,:endDateText)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@skip_footer = true
  	@skip_header = true
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/competitions/_form.html.erb
<div class="formssComp container">
  <div id="wrapper">
      <div id="box">  
        <div class="header">
          <h4><strong>Enter Competition Details</strong></h4>
        </div>
          



          <%= form_for(@competition) do |f| %>
              <% if @competition.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

                  <ul>
                  <% @competition.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>


              <h5>EVENT NAME</h5>
              <%= f.text_field :name, autofocus: true, class: "form-control" , :placeholder => "eg. Quizzical", :autocomplete => :off%>

              <h5>EVENT CATEGORY</h5>

              
              
                <div class="btn-group btn-input clearfix">
                   <button type="button" class="btn btn-default dropdown-toggle form-control"  data-toggle="dropdown">
                      <div class="selectText">
                        <span data-bind="label" >Select One</span>&nbsp;<span class="caret"></span>
                      </div>
                   </button>
                   <ul class="dropdown-menu categ" role="menu">
                     
                              <li><a >Board Games</a></li>
                              <li><a >Bussiness Plan</a></li>
                              <li><a >Dance</a></li>
                              <li><a >Design</a></li>
                              <li><a >Debate</a></li>
                              <li><a >Electronics Design </a></li>
                              <li><a >MUN</a></li>
                              <li><a >Music</a></li>                                
                              <li><a >Programming</a></li>
                              <li><a >Quiz</a></li>
                              <li><a >Robotics</a></li>
                              <li><a >Sports</a></li>
                              <li><a >Technical Paper Presentation</a></li>
                              <li role="presentation" class="divider"></li>
                              <li><a >Miscellaneous</a></li>
                   </ul>

                 </div>
                 <input type="hidden" class="form-control" name="competition[category]" id="competition_category"/>      

              <h5>BRIEF DESCRIPTION</h5>
              <%= f.text_field :description, class: "form-control" , :placeholder => "A Bussiness and Economy Quiz", :autocomplete => :off%>

            
              <h5>COLLEGE / COMPANY NAME</h5>
              <%= f.text_field :collegename, class: "form-control" , :placeholder => "Adobe",:autocomplete => :off%>

              <h5>ORGANIZED BY</h5>
              <%= f.text_field :organizedBy, class: "form-control",  :placeholder => "The Quiz Club at Adobe  |  [Fest name/Club name/Fete name]" ,:autocomplete => :off%>

              <h5>LOCATION</h5>
              <input class="form-control" type="text" name="competition[location]" id="competition_location">

              <h5>ONLINE/ONSITE EVENT</h5>
              <div class="btn-group btn-input clearfix">
                   <button type="button" class="btn btn-default dropdown-toggle form-control"  data-toggle="dropdown">
                      <div class="selectText">
                        <span data-bind="label" >Select</span>&nbsp;<span class="caret"></span>
                      </div>
                   </button>
                   <ul class="dropdown-menu onOff" role="menu">
                              
                              <li><a >Online</a></li>
                              <li><a >Onsite</a></li>
                              
                   </ul>

                 </div>
              <input type="hidden" class="form-control" name="competition[onOff]" id="competition_onOff"/>  

              <h5>TOTAL PRIZE MONEY[Rupees]</h5>
              <div class="prizeMoney">
                <input class="form-control"  type="number" name="competition[money]" id="competition_money"
                    min="0" max="100000" step="1000" maxlength="6" >
              </div>

              <h5>WEBSITE</h5>
              <%= f.text_field :linkWebsite, class: "form-control", :placeholder => "Enter the link of the events website"%>

              <h5>FB PAGE</h5>
              <%= f.text_field :linkFb, class: "form-control", :placeholder => "Enter the link of the events FB page" %>

              
               <h5>STARTS AT</h5>
               
              <div class="y">
                  <div class="x">
                      <input type='text' class="form-control" name="competition[startDateText]" id="competition_startDateText"/>
                  </div>
              </div>


              <h5>ENDS AT</h5>
              <div class="y">
                  <div class="x">
                      <input type='text' class="form-control" name="competition[endDateText]" id="competition_endDateText"/>
                  </div>
              </div>
              



              <%= f.submit class: "btn btn-primary" %>


    
          <% end %>

      </div>
     
    </div>
</div>



             

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<div class="container">
  <div id="comp" class="transitions-enabled">
      <% @competitions.each do |competition| %>
        <div class="masonry-item ">
          <div class="panel-body">
            <%= competition.name %>
            <%= competition.user.email if competition.user%><br/>
            <%= competition.description %><br/>
            <%= competition.category %><br/>
            <%= competition.collegename %><br/>
            <%= competition.money %><br/>
            <%= link_to 'Show', competition %>
            
            <% if competition.user == current_user %>
              <div class="actions">
                <%= link_to 'Edit', edit_competition_path(competition) %>
                <%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            <% end %>
          </div>
        </div>


      <% end %>
  </div>
    
  <div class="center">
     <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/competitions/new.html.erb
	<%= render 'form' %>


<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<div class="container">
	<div class="row" id="moreInfo">
		<div class="col-sm-6">
			<strong><h3><%= @competition.name %></h3></strong>
			<div class="tabbable">
				<ul class="nav nav-tabs">
					<li class="active"><a href="#tab1" data-toggle="tab">Where</a></li>	
					<li><a href="#tab2" data-toggle="tab">More Details</a></li>
							
				</ul>
				<div class="tab-content">
					<div class="tab-pane" id="tab2">
						<h4>Logo</small></h4>
						
						<img src="http://placehold.it/140" class="thumbnail pull-left" alt="Placeholder image">
						
						
						
						<hr>
						<p>The action starts at <%= @competition.startDateText %> </p>
						
						
					</div><!-- end tab-pane -->
					<div class="tab-pane active" id="tab1">
						<h4><span class="glyphicon glyphicon-map-marker"></span> Our Location </h4>
						
						<iframe width="100%" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/?q=<%= @competition.location %>&output=embed"></iframe>
						
						<p><h4><%= @competition.location %></h4></p>
					</div><!-- end tab-pane -->
					
					
				</div><!-- end tab-content -->
			</div><!-- end tabbable -->

		</div>
		<div class="col-sm-6">
			<strong><h3><%= @competition.category %></h3></strong>
			
			
			<div class="list-group">
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading"><%= @competition.onOff %></h4>
					
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading"><%= @competition.description %></h4>
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">Organized By:
						  <%= @competition.organizedBy %></h4>
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">FB link:
						  <%= @competition.linkFb %></h4>
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">Website:
						  <%= @competition.linkWebsite %></h4>
				</a>
			</div><!-- list-group -->
			
			
		</div><!-- end col-sm-6 -->
				
	</div>



	<button class="btn btn-warning" ><%= link_to 'Back', competitions_path %></button>
	<% if @competition.user == current_user %>
				<button class="btn btn-warning" ><%= link_to 'Edit', edit_competition_path(@competition)%></button>		  
	<% end %>
</div>

app/views/layouts/_footer.html.erb
 <div class="landingPage">
     <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                    <div class="row">
                        <div class="footer-col col-md-4">
                        <h3>Suggestions?</h3>
                        <p>Mail us at </p>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>Around the Web</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                            </li>
                            <li>
                                <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                            </li>

                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>About Cmpete</h3>
                        <p>Cmpete is a f</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Cmpete.com 2015
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default ">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../competitions">CMPETE!</a>
    </div>
    <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search competitions">
        </div>
       
    </form>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      
      <ul class="nav navbar-nav navbar-right">

        <li >
          <p class="createComp"><a href="/competitions/new" class="btn btn-success btn-small" background-color="#2ecc71"><font color="white">Create Competition</font></a> </p></li>
        

        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Me<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Saved Contests</a></li>
            <li><a href="#">Registered Contests</a></li>
            <li class="divider"></li>
            <li><a href="#">Created Events</a></li>
          </ul>
        </li>
        <% else %>
          <li><a href="/users/sign_up">Sign up</a></li>
          <li><a href="/users/sign_in">Log in</a></li>
        <% end %>
         
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Protone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--<link rel='stylesheet' media='screen and (max-width: 767px)' href='../../../../app/assets/stylesheets/media.css' />-->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&libraries=places&language=en-US"></script>
  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= render 'layouts/shim' %>
  
</head>
<body>
	<%= render "layouts/header" unless @skip_header %>
  <div class="flash-message">
    <% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "alert alert-success alert-block fade in") %>
    <% end %>
  </div>

	
          <%= yield %>


  
  <%= render "layouts/footer" unless @skip_footer %>



</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="landingPage">
    <div id="page-top" class="index">

        <!-- Navigation -->
        

        <!-- Header -->
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <img class="img-responsive" src="/profile.png" alt="">
                        <div class="intro-text">
                            <span class="name">Cmpete</span>
                            <hr class="star-light">
                            <span class="skills">Your competitions belong here!</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Portfolio Grid Section -->
        <section id="contact">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2>Early Access</h2>
                        <hr class="star-primary">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                        <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                        <form name="sentMessage" id="contactForm" autocomplete="off">
                            <div class="row control-group">
                                <div class="form-group col-xs-12 floating-label-form-group controls">
                                    <label>Access Code</label>
                                    <input type="text" class="form-control" placeholder="Access Code" id="accessCode" >
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            
                            <br>
                            <div id="success"></div>
                            <div class="row">
                                 <div class="form-group col-xs-5">
                                    
                                </div>

                                <div class="form-group col-xs-4 letMeIn">
                                    <button type="submit"  class="btn btn-success btn-lg">Let me in</button>
                                </div>

                                 <div class="form-group col-xs-4">
                                    
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </section>

        <!-- About Section -->
        <section class="success" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-center">
                        <h2>About</h2>
                        <hr class="star-light">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-lg-offset-2">
                        <p>Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.</p>
                    </div>
                    <div class="col-lg-4">
                        <p>Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!</p>
                    </div>
                    
                </div>
            </div>
        </section>

        <!-- Contact Section -->
        

        <!-- Footer -->
        <footer class="text-center">
            <div class="footer-above">
                <div class="container">
                    <div class="row">
                        <div class="footer-col col-md-4">
                            
                        </div>
                        <div class="footer-col col-md-4">
                            <h3>Around the Web</h3>
                            <ul class="list-inline">
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                                </li>
                                
                            </ul>
                        </div>
                        <div class="footer-col col-md-4">
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-below">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            Copyright &copy; Cmpete.com 2015
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
        <div class="scroll-top page-scroll visible-xs visble-sm">
            <a class="btn btn-primary" href="#page-top">
                <i class="fa fa-chevron-up"></i>
            </a>
        </div>

        <!-- Portfolio Modals -->
        <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-content">
                <div class="close-modal" data-dismiss="modal">
                    <div class="lr">
                        <div class="rl">
                        </div>
                    </div>
                </div>
                
        

        

    </div>
</div>